write-host "Chrome:           $([Microsoft.PowerShell.Commands.PSUserAgent]::Chrome          )"
write-host "FireFox:          $([Microsoft.PowerShell.Commands.PSUserAgent]::FireFox         )"
write-host "InternetExplorer: $([Microsoft.PowerShell.Commands.PSUserAgent]::InternetExplorer)"
write-host "Opera:            $([Microsoft.PowerShell.Commands.PSUserAgent]::Opera           )"
write-host "Safari:           $([Microsoft.PowerShell.Commands.PSUserAgent]::Safari          )"
